config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :wikis

  resources :charges
  
  get 'welcome/index'

  get 'welcome/about' 

  get 'charges/create'

  root to: 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  has_many :collaborators
  has_many :users, through: :collaborators_users
end

app/models/collaborator_user.rb
class CollaboratorUser < ActiveRecord::Base
  belongs_to :collaborator 
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :collaborators_users
  has_many :collaborators, through: :collaborators_users
  has_many :roles

  scope :visible_to, -> (user) { user ? all : where(public: true) }

  def admin?
    role == 'admin'
  end

  def premium?
    role == 'premium'
  end

  def standard?
    role == 'standard'
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  default_scope{ order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
  #Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end

  def show
    @user = User.find(params[:id])
    @wikis = @user.wikis.visible_to(current_user)
  end

  def index
    @users = User.top_rated.paginate(page: params[:page], per_page: 10)
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.paginate(page: params[:page], per_page: 5)
  end

  def show
    @wikis = Wiki.find(params[:id])
    authorize @wikis
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(params.require(:wiki).permit(:title, :body))
    @wiki.user = current_user
    authorize @wiki
    if @wiki.save
      flash[:notie] = "Wiki was saved!"
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the wiki. Please try again."
      render :new
    end 
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end


  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(params.require(:wiki).permit(:title, :body))
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wikis = Wiki.find(params[:id])
    
    authorize @wikis
    if @wikis.destroy
      flash[:notice] = "\"#{@wikis.title}\" was deleted successfully."
    else
      flash[:error] = "There was an error deleting the wiki, please try again."
      return render :edit
    end
    redirect_to wikis_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=divice-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   </head>
  <body>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>

  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
    </div>

  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <div class="user-info">
    <% if current_user %>
      Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %> /
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %> or
      <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>

    <%= yield %>

    <div class="row">
     <% if policy(Wiki.new).create? %>
        <%= link_to "New Wiki", new_wiki_path %> /
      <% end %> 
      <%= link_to "Home Page", root_path %> /
      <%= link_to "About Blocipedia", welcome_about_path %> 
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/welcome/about.html.erb
<div class="container">
  <div class="form-group">
    <h1>Welcome to Blocipedia</h1>
    <p>Create as many public wikis as you want, sign up for a <%= link_to "standard membership", new_user_registration_path %>!</p>
    <p>Create Private wikis, sign up for a <%= link_to "premium membership", new_charge_path %>!</p>
    <p><%= link_to "Home Page", root_path %></p>
  </div>
</div>

app/views/welcome/index.html.erb
  <div class="container">
    <div class="form-group">
      <h1>Welcome to Blocipedia</h1>
        <p>Where you can create and share Wikis!</p>
        <p>Created by: <%= link_to "Jackie", "https://www.facebook.com/profile.php?id=100009465465751" %></p>
    </div> 

  <% if current_user.present? %>
    <p><%= link_to "View Wikis", wikis_path %></p> or
    <p><%= link_to "Create New Wiki", new_wiki_path %></p>
  <% else %>
    <p><%= link_to "Sign In", new_user_session_path %> to your account </p> or <br>
    <p><%= link_to "Sign Up", new_user_registration_path %> to start creating and sharing Wikis.</p>
    <p><%= link_to "About Blocipedia", welcome_about_path %></p>
   <% end %> 
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <% if current_user.present? %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    </div> 

    <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private Wiki
    </div> 

    <div class="form-group">
      <%= f.submit "Save" %>
    <% end %>
    </div> 
 <% end %>
<% end %>

app/views/wikis/edit.html.erb
<div class="container">
  <div class="form-group">
    <h1>Edit Wiki</h1>
      <%= render partial: "form" %>
    <% if policy(@wiki).destroy? %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this Wiki?' } %></br>
    <% end %>
  </div>

  <div class="form-group">
    <%= link_to "Return to Wiki's list", wikis_path %>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="container">
  <h1>Wikis</h1>

  <% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to wiki.title, wiki %>
        </h4>
      </div>
    </div>
  <% end %>
  <%= will_paginate @wikis %>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<div class="container">
  <%= render partial: "form" %>
  <%= link_to "Wiki's list", wikis_path %>
</div>

app/views/wikis/show.html.erb
<div class="container">
  <h2><%= markdown_to_html @wikis.title %></h2>
  
  <div class='form-group'>
    <%= @wikis.body %>
  </div>   
    <br>
    <% if policy(@wikis).edit? %>
      <%= link_to "Edit this Wiki", edit_wiki_path %> /
      <%= link_to "Return to Wiki's list", wikis_path %><br>
    <% end %>
</div> 